-- ══════════════════════════════════════════════════════════════════════════════
-- Digital Aptitude Evaluation System — Complete Database Schema
-- ══════════════════════════════════════════════════════════════════════════════
--
-- HOW TO USE IN pgAdmin:
--   1. Open pgAdmin and create a new database named "aptitude_db"
--   2. Right-click the database → Query Tool
--   3. Paste this entire file and click Execute (F5)
--
-- HOW TO USE WITH psql:
--   psql -U postgres -d aptitude_db -f db/schema.sql
--
-- This script is fully idempotent — safe to re-run on an existing database
-- without losing data (all CREATE statements use IF NOT EXISTS, all INSERTs
-- use ON CONFLICT … DO NOTHING / DO UPDATE).
--
-- ══════════════════════════════════════════════════════════════════════════════


-- ── Admins ────────────────────────────────────────────────────────────────────
-- Two roles:
--   super_admin   — full access (settings, passcodes, admin management)
--   general_admin — read-only dashboard / results

CREATE TABLE IF NOT EXISTS admins (
    id            SERIAL PRIMARY KEY,
    username      VARCHAR(100) UNIQUE NOT NULL,
    password_hash TEXT        NOT NULL,
    role          VARCHAR(30) NOT NULL DEFAULT 'general_admin'
                    CHECK (role IN ('super_admin', 'general_admin')),
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);

-- Default super admin (username: admin | password: admin123)
INSERT INTO admins (username, password_hash, role, is_active)
VALUES ('admin', '$2a$10$jAf3YJPlTSPg0aVSjhlcdONGwEW5dM42Nh/URf6vCB5y.5Yc7/frW', 'super_admin', TRUE)
ON CONFLICT (username) DO UPDATE SET role = 'super_admin', is_active = TRUE;


-- ── Admin Sessions ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS admin_sessions (
    id            SERIAL PRIMARY KEY,
    admin_id      INT  REFERENCES admins(id) ON DELETE CASCADE,
    session_token TEXT UNIQUE NOT NULL,
    expires_at    TIMESTAMP   NOT NULL,
    created_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);


-- ── Passcodes ─────────────────────────────────────────────────────────────────
-- Reusable access codes generated by super admins.
-- Expiry duration is controlled by test_config.passcode_validity_minutes.

CREATE TABLE IF NOT EXISTS passcodes (
    id         SERIAL PRIMARY KEY,
    code       VARCHAR(100) UNIQUE NOT NULL,
    expires_at TIMESTAMP    NOT NULL DEFAULT (CURRENT_TIMESTAMP + INTERVAL '90 minutes'),
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);


-- ── Participants ──────────────────────────────────────────────────────────────
-- One row per registered test-taker.
-- cid_number is unique — a person can only register once.

CREATE TABLE IF NOT EXISTS participants (
    id             SERIAL PRIMARY KEY,
    full_name      VARCHAR(150) NOT NULL,
    cid_number     VARCHAR(50)  NOT NULL UNIQUE,
    company_name   VARCHAR(150) NOT NULL,
    contact_number VARCHAR(50)  NOT NULL,
    passcode_id    INT REFERENCES passcodes(id),
    started_at     TIMESTAMP,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ── Questions ─────────────────────────────────────────────────────────────────
-- question_type:
--   'mcq'        — four or five options (option_a … option_e); correct answer is A/B/C/D/E
--   'fill_blank' — options are empty; correct answer is comma-separated keywords
--                  (any single keyword match, case-insensitive, counts as correct)

CREATE TABLE IF NOT EXISTS questions (
    id            SERIAL PRIMARY KEY,
    section       VARCHAR(100) NOT NULL,
    question_text TEXT         NOT NULL,
    question_type VARCHAR(20)  NOT NULL DEFAULT 'mcq',
    option_a      TEXT         NOT NULL DEFAULT '',
    option_b      TEXT         NOT NULL DEFAULT '',
    option_c      TEXT         NOT NULL DEFAULT '',
    option_d      TEXT         NOT NULL DEFAULT '',
    option_e      TEXT         NOT NULL DEFAULT '',
    image_url     TEXT,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
-- Idempotent migration for databases created before option_e was added.
ALTER TABLE questions ADD COLUMN IF NOT EXISTS option_e TEXT NOT NULL DEFAULT '';


-- ── Answers ───────────────────────────────────────────────────────────────────
-- One row per question.
-- MCQ:        correct_option is 'A', 'B', 'C', or 'D'
-- fill_blank: correct_option is comma-separated accepted keywords
--             e.g. "Paris, paris, the capital of France"

CREATE TABLE IF NOT EXISTS answers (
    id             SERIAL PRIMARY KEY,
    question_id    INT  UNIQUE REFERENCES questions(id) ON DELETE CASCADE,
    correct_option TEXT NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ── Submissions ───────────────────────────────────────────────────────────────
-- One row per completed test attempt.
-- participant_id is UNIQUE — one submission per participant, enforced at DB level.
-- Legacy per-section columns (analytical_score, verbal_score, quantitative_score)
-- are kept for backward compatibility; detailed per-section data lives in
-- submission_section_scores.

CREATE TABLE IF NOT EXISTS submissions (
    id                  SERIAL PRIMARY KEY,
    participant_id      INT UNIQUE REFERENCES participants(id) ON DELETE CASCADE,
    submitted_at        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    score               INT           DEFAULT 0,
    total_questions     INT           DEFAULT 0,
    percentage          NUMERIC(5,2)  DEFAULT 0,
    analytical_score    INT           DEFAULT 0,
    verbal_score        INT           DEFAULT 0,
    quantitative_score  INT           DEFAULT 0
);

-- Explicit unique index (covers databases where the column-level UNIQUE was
-- not applied at table-creation time).
CREATE UNIQUE INDEX IF NOT EXISTS submissions_participant_id_unique
    ON submissions(participant_id);


-- ── Participant Answers ───────────────────────────────────────────────────────
-- One row per question per submission.
-- selected_option is TEXT to support both A/B/C/D (MCQ) and free-text (fill_blank).

CREATE TABLE IF NOT EXISTS participant_answers (
    id              SERIAL PRIMARY KEY,
    submission_id   INT  REFERENCES submissions(id)  ON DELETE CASCADE,
    question_id     INT  REFERENCES questions(id)    ON DELETE CASCADE,
    selected_option TEXT,
    is_correct      BOOLEAN DEFAULT FALSE
);


-- ── Per-submission Section Scores ─────────────────────────────────────────────
-- Stores one row per section per submission so historical scores remain correct
-- even if the section configuration changes after the test was taken.

CREATE TABLE IF NOT EXISTS submission_section_scores (
    id              SERIAL PRIMARY KEY,
    submission_id   INT          NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    section_name    VARCHAR(100) NOT NULL,
    score           INT          NOT NULL DEFAULT 0,
    questions_count INT          NOT NULL DEFAULT 0
);


-- ── Test Configuration ────────────────────────────────────────────────────────
-- Singleton row (id = 1). Super admins can change these via the Settings page.

CREATE TABLE IF NOT EXISTS test_config (
    id                        INT PRIMARY KEY DEFAULT 1,
    test_duration_minutes     INT  NOT NULL DEFAULT 60,
    passcode_validity_minutes INT  NOT NULL DEFAULT 90,
    test_title                TEXT NOT NULL DEFAULT 'Online Aptitude Test',
    updated_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by                INT REFERENCES admins(id)
);

ALTER TABLE test_config ADD COLUMN IF NOT EXISTS test_title TEXT NOT NULL DEFAULT 'Online Aptitude Test';

INSERT INTO test_config (id, test_duration_minutes, passcode_validity_minutes, test_title)
VALUES (1, 60, 90, 'Online Aptitude Test')
ON CONFLICT (id) DO NOTHING;


-- ── Test Sections ─────────────────────────────────────────────────────────────
-- Each row defines one section that appears in the test.
-- questions_per_test: how many questions are drawn randomly per participant.
-- label: short display label shown in the admin UI (e.g. "Section A").
-- Deleting a section also deletes all its questions (handled in app layer).

CREATE TABLE IF NOT EXISTS test_sections (
    id                 SERIAL PRIMARY KEY,
    name               VARCHAR(100) NOT NULL UNIQUE,
    label              VARCHAR(50)  NOT NULL DEFAULT '',
    questions_per_test INT          NOT NULL DEFAULT 16,
    sort_order         INT          NOT NULL DEFAULT 0,
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);


-- ── Performance Indexes ───────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS participant_answers_submission_id_idx
    ON participant_answers(submission_id);

CREATE INDEX IF NOT EXISTS submission_section_scores_submission_id_idx
    ON submission_section_scores(submission_id);
